version: '2'
services:
    nitro-app:
        image: nitro
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nitro-postgresql:5432/nitro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://nitro-elasticsearch:9200
        ports:
            - 8080:8080
    nitro-postgresql:
        extends:
            file: postgresql.yml
            service: nitro-postgresql
    nitro-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: nitro-elasticsearch
