version: '2'
services:
    nitrocarriers-app:
        image: nitrocarriers
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nitrocarriers-postgresql:5432/NitroCarriers
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nitrocarriers-postgresql:
        extends:
            file: postgresql.yml
            service: nitrocarriers-postgresql
