name: Application CI
on: [push, pull_request]
jobs:
    applications:
        name: Nitro Carriers test suite
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            NODE_VERSION: 16
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '8'
                  cache: 'gradle'
            - name: Install node.js packages
              run: npm install
            - name: Run backend test
              run: |
                 chmod +x gradlew
                 ./gradlew test
            - name: Run frontend test
              run: npm run test
            - name: Package application
              run: ./gradlew -Pprod clean bootWar
